apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve-ocr-pipeline
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/maalwis/kserve-ocr-pipeline
    targetRevision: HEAD
    path: kubernetes
  destination: 
    server: https://kubernetes.default.svc
    namespace: kserve-ocr

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true